export const NETWORKS = [
  { id: "eth", name: "Ethereum", symbol: "ETH" },
  { id: "bsc", name: "BNB Chain", symbol: "BNB" },
  { id: "polygon", name: "Polygon", symbol: "MATIC" },
  { id: "arbitrum", name: "Arbitrum One", symbol: "ARB" },
  { id: "optimism", name: "Optimism", symbol: "OP" },
  { id: "base", name: "Base", symbol: "ETH" },
  { id: "zksync", name: "zkSync Era", symbol: "ETH" },
  { id: "linea", name: "Linea", symbol: "ETH" },
  { id: "scroll", name: "Scroll", symbol: "ETH" },
  { id: "manta", name: "Manta Pacific", symbol: "ETH" },
  { id: "opbnb", name: "opBNB", symbol: "BNB" },
  { id: "tron", name: "TRON", symbol: "TRX" },
  { id: "solana", name: "Solana", symbol: "SOL" },
  { id: "okc", name: "OKT Chain", symbol: "OKT" },
  { id: "sui", name: "Sui", symbol: "SUI" },
  { id: "aptos", name: "Aptos", symbol: "APT" },
  { id: "cosmos", name: "Cosmos Hub", symbol: "ATOM" },
  { id: "kava", name: "Kava", symbol: "KAVA" }
] as const;